language: node_js
sudo: false
node_js:
  - "0.12"
env:
  global:
    - secure: U4CyMK+05vj8bJNu9SnF4+HPRRAcvmsjq/sdvxJFJdtt15KMyDdcxFZW5VaBn5Ll87TtaMJb/SyI3Z+VcxOdIqwsDJNKETROkvr+/onhQuKtAEXFFqUjseoPrIvijXs1zUQzJ0bZqnEKWjOpCxht1C3liWasPhA+NfdQFwMhkrk=
    - secure: PthUvoUKmz6Oh1fyWNwLNQyvPyMOC4bvn9AwaUNQX71OOatxy6ZDpukKt6ujR5aj6Mbm/3IZuoWTgfPGDTbXCUWj93cUG/RrPiNjAw8F41m5krQa/qU9SjBTswNFgZMKk6JTo2L4BA1YMPim8i/ALteFPc1LpdDqJ/3uKm33OLs=
