language: node_js
sudo: false
node_js:
- '0.12'
env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: qkWX5gf0X+gtcshX4U5OBdozj/q8TjPcE8IArromTei+uzpzKwYsgNORLdSvp8pQCWGUUIiFeOATZdGCRktyf+h3UgbqkvsLsH2sREhYhcKJ+Ub9eQfNdd/OioJszA+Jm0FRPw+GWRQW/aftSVk8AZYgKzA9Cj3xR+RkaXrr7ic=
  - secure: QVJAPe19yXtAoQB3q+9GSTifw8qV63RDyXiILCtVLKy3e8MHMwuQszIk/2nnjn61WL3Gat+Ch1X9NOUw++TwrEl/VlIyR9J8P4e87sCegOoZygSN98VZwB+7r/WNm1ChpmYOMya6WrDHNKFGxRPc4Q/z2QB86eqbBqf54xG4k/8=
